version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - db
      - redis

  db:
    image: postgres:15.8-bookworm
    container_name: postgres_db
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.11-alpine3.17
    container_name: redis_cache
    restart: always
    volumes:
      - redis_data:/data

  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx_proxy
    ports:
      - "8080:80"
    depends_on:
      - app

volumes:
  db_data:
  redis_data:
