version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_PORT=${APP_PORT}
        - APP_ENV=${APP_ENV}
    container_name: go_app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    volumes:
      - assets:/usr/src/app/assets:Z
    ports:
      - 8888:8888
    depends_on:
      - db
      - redis

  db:
    image: postgres:15.8-bookworm
    container_name: postgres_db
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data:Z

  redis:
    image: redis:7.4-bookworm
    container_name: redis_cache
    restart: always
    volumes:
      - redis_data:/data:Z

  nginx:
    image: nginx:1.26.2-bookworm
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - assets:/app:Z
    depends_on:
      - app

volumes:
  db_data:
  redis_data:
  assets:
